add variables and improve scripts

diff --git a/ansible/roles/master/files/create-join-script b/ansible/roles/master/files/create-join-script
--- a/ansible/roles/master/files/create-join-script
+++ b/ansible/roles/master/files/create-join-script
@@ -2,4 +2,25 @@
 
 set -e
 
-echo "kubeadm join 192.168.56.10:6443 --token $(kubeadm-token) --discovery-token-ca-cert-hash sha256:$(kubeadm-hash)" > /home/vagrant/join.sh
+MASTER=""
+
+for i in "$@"; do
+  case $i in
+    --master=*)
+      MASTER="${i#*=}"
+      shift
+      ;;
+    *)
+      MASTER+=("$1")
+      shift
+      ;;
+  esac
+done
+
+
+if [[ -z $MASTER ]]; then
+  echo "Missing required parameter --master"
+  exit 1
+fi
+
+echo "kubeadm join ${MASTER}:6443 --token $(kubeadm-token) --discovery-token-ca-cert-hash sha256:$(kubeadm-hash)" > /home/vagrant/join.sh
